## Aim:
Introduction to Numpy

### What is NumPy?
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.  

It has the following features: 
1. Powerful N-dimensional arrays  
Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

2. Numerical computing tools  
NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

3. Interoperable  
NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

4. Performant  
The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

5. Easy to use  
NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

6. Open source

#### Advantages over a list:

- Consumes less memory.
- Fast as compared to the python List.
- Convenient to use.

In [43]:
import numpy as np

In [111]:
a = [1,2,3]
b = np.array(a)
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [112]:
a = [1,2,3,4,'5']
b = np.array(a)
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [113]:
#now checking the data type of 5th element
print(type(b[4]))

<class 'numpy.str_'>


In [114]:
c= np.array(a, dtype=int)
print(type(c[4]))

<class 'numpy.int64'>


In [115]:
arr=np.ones(3,dtype=int)
arr

array([1, 1, 1])

In [116]:
arr1 = np.zeros(3,dtype=int)
arr1

array([0, 0, 0])

In [117]:
arr2=np.identity(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
arr3 = np.eye(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
# arr2 = np.identity(3,4)
#this wont work because identity matrix needs to be symmetric

But we can create a non-square matric using eye

In [120]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [121]:
np.full(3,5)

array([5, 5, 5])

In [122]:
np.full(4,7)

array([7, 7, 7, 7])

Creating a 2x2 array using the above one:

In [123]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### np.arange()
syntax: `np.arange(start, stop, step, dtype)`

In [124]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.arange(5,9)

array([5, 6, 7, 8])

In [126]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [127]:
np.arange(2,20,2,float)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [128]:
np.linspace(0,9)
#by default 50 samples are generated

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [129]:
np.linspace(5,20,7)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [130]:
#by default the end point is included in the result
np.linspace(-10,5,10,endpoint=True)

array([-10.        ,  -8.33333333,  -6.66666667,  -5.        ,
        -3.33333333,  -1.66666667,   0.        ,   1.66666667,
         3.33333333,   5.        ])

In [101]:
#excluding the end point
np.linspace(-10,5,10,endpoint=False)

array([-10. ,  -8.5,  -7. ,  -5.5,  -4. ,  -2.5,  -1. ,   0.5,   2. ,
         3.5])

In [110]:
#creates random array with numbers b/w 0 and 1
np.random.rand(2,10)  #to create a 2x10 array

array([[0.48430904, 0.45172127, 0.51882281, 0.7813788 , 0.256045  ,
        0.25259297, 0.71034435, 0.83194907, 0.23498478, 0.08008148],
       [0.60868668, 0.79364399, 0.70939336, 0.01093018, 0.25872202,
        0.58524117, 0.72522345, 0.18477845, 0.15224051, 0.22354685]])